spring.application.name=taskmanager
spring.datasource.url=${SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/taskmanager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:taskuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:taskpass}

#Switch later to flyaway to make database migrations instead of hibernate auto update schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
